create or replace table analytic_mart.pre_inventory_store_sku as
select
chain_id
,store_id
,week_id
,style_id
,FARM_FINGERPRINT(cast(style_id as string)) as style_key
,color_id
--,size_id
,sku_id
,FARM_FINGERPRINT(cast(sku_id as string)) as item_key
,bop_store_inv_cnt
,bop_store_inv_amt
,bop_store_inv_actual_amt
,bop_store_inv_value_amt
,bop_store_it_cnt
,bop_store_it_amt
,bop_store_it_actual_amt
,bop_store_it_value_amt
,store_receipt_cnt
,store_receipt_amt
,store_receipt_actual_amt
,store_receipt_value_amt
,bop_mkd_store_it_cnt
,bop_mkd_store_it_amt
,bop_mkd_store_it_actual_amt
,bop_mkd_store_it_value_amt
,dmos_cnt
,dmos_amt
,dmos_actual_amt
,dmos_value_amt
,store_trans_out_cnt
,store_trans_out_amt
,store_trans_out_actual_amt
,store_trans_out_value_amt
,store_trans_in_cnt
,store_trans_in_amt
,store_trans_in_actual_amt
,store_trans_in_value_amt
,bop_alloc_notship_inv_cnt
,bop_alloc_notship_inv_amt
,bop_alloc_notship_actual_amt
,bop_alloc_notship_value_amt
,mkd_issue_cnt
,mkd_issue_amt
,mkd_issue_cost_amt
,bop_store_mkd_it_cnt
,bop_store_mkd_it_amt
,bop_store_mkd_it_actual_amt
from
demand_forecast.inventory_store_sku