#!/usr/bin/bash

. ${HOME}/lib/set_env.sh
. ${HOME}/lib/common.sh

archive_bucket_files 'gs://p-ascena-aadp-landing-01/pre/atg/*.txt'
archive_bucket_files 'gs://p-ascena-aadp-landing-01/pre/aw/*.dat'
archive_bucket_files 'gs://p-ascena-aadp-landing-01/pre/bi/*.DAT'
archive_bucket_files 'gs://p-ascena-aadp-landing-01/pre/dom/*.dat'
archive_bucket_files 'gs://p-ascena-aadp-landing-01/pre/sapd/*.dat'
archive_bucket_files 'gs://p-ascena-aadp-landing-01/pre/sapwm/*.dat'


gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_RETURNS_20200218.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_RETURNS_20200218.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_RETURNS_20200219.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_RETURNS_20200219.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_RETURNS_20200220.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_RETURNS_20200220.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_RETURNS_20200221.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_RETURNS_20200221.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_RETURNS_20200222.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_RETURNS_20200222.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_RETURNS_20200223.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_RETURNS_20200223.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_RETURNS_20200224.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_RETURNS_20200224.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_TRANSACTIONS_20200218.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_TRANSACTIONS_20200218.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_TRANSACTIONS_20200219.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_TRANSACTIONS_20200219.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_TRANSACTIONS_20200220.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_TRANSACTIONS_20200220.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_TRANSACTIONS_20200221.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_TRANSACTIONS_20200221.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_TRANSACTIONS_20200222.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_TRANSACTIONS_20200222.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/atg/arc/ANN_ATG_TRANSACTIONS_20200223.txt gs://p-ascena-aadp-landing-01/pre/atg/ANN_ATG_TRANSACTIONS_20200223.txt &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200218.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200219.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200220.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200221.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200221.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200222.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200222.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200223.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200223.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200224.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_DISCOUNTDTL_20200224.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_HEADER_20200218.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_HEADER_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_HEADER_20200219.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_HEADER_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_HEADER_20200220.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_HEADER_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_HEADER_20200221.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_HEADER_20200221.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_HEADER_20200222.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_HEADER_20200222.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_HEADER_20200223.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_HEADER_20200223.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_HEADER_20200224.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_HEADER_20200224.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINENOTES_20200218.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINENOTES_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINENOTES_20200219.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINENOTES_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINENOTES_20200220.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINENOTES_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINENOTES_20200221.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINENOTES_20200221.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINENOTES_20200222.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINENOTES_20200222.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINENOTES_20200223.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINENOTES_20200223.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINENOTES_20200224.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINENOTES_20200224.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINE_20200218.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINE_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINE_20200219.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINE_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINE_20200220.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINE_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINE_20200221.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINE_20200221.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINE_20200222.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINE_20200222.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINE_20200223.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINE_20200223.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_LINE_20200224.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_LINE_20200224.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_MERCHDTL_20200218.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_MERCHDTL_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_MERCHDTL_20200219.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_MERCHDTL_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_MERCHDTL_20200220.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_MERCHDTL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_MERCHDTL_20200221.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_MERCHDTL_20200221.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_MERCHDTL_20200222.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_MERCHDTL_20200222.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_MERCHDTL_20200223.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_MERCHDTL_20200223.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_MERCHDTL_20200224.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_MERCHDTL_20200224.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_RETURNDTL_20200218.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_RETURNDTL_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_RETURNDTL_20200219.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_RETURNDTL_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_RETURNDTL_20200220.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_RETURNDTL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_RETURNDTL_20200221.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_RETURNDTL_20200221.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_RETURNDTL_20200222.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_RETURNDTL_20200222.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_RETURNDTL_20200223.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_RETURNDTL_20200223.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_RETURNDTL_20200224.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_RETURNDTL_20200224.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_TAXDETAIL_20200218.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_TAXDETAIL_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_TAXDETAIL_20200219.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_TAXDETAIL_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_TAXDETAIL_20200220.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_TAXDETAIL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_TAXDETAIL_20200221.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_TAXDETAIL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_TAXDETAIL_20200222.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_TAXDETAIL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_TAXDETAIL_20200223.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_TAXDETAIL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/aw/arc/ANN_AW_TRANSACTIONS_TAXDETAIL_20200224.dat gs://p-ascena-aadp-landing-01/pre/aw/ANN_AW_TRANSACTIONS_TAXDETAIL_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/bi/arc/ANN_BI_TRANSACTION_FPNFP_20200218.DAT gs://p-ascena-aadp-landing-01/pre/bi/ANN_BI_TRANSACTION_FPNFP_20200218.DAT &
gsutil cp gs://p-ascena-aadp-landing-01/pre/bi/arc/ANN_BI_TRANSACTION_FPNFP_20200219.DAT gs://p-ascena-aadp-landing-01/pre/bi/ANN_BI_TRANSACTION_FPNFP_20200219.DAT &
gsutil cp gs://p-ascena-aadp-landing-01/pre/bi/arc/ANN_BI_TRANSACTION_FPNFP_20200220.DAT gs://p-ascena-aadp-landing-01/pre/bi/ANN_BI_TRANSACTION_FPNFP_20200220.DAT &
gsutil cp gs://p-ascena-aadp-landing-01/pre/bi/arc/ANN_BI_TRANSACTION_FPNFP_20200221.DAT gs://p-ascena-aadp-landing-01/pre/bi/ANN_BI_TRANSACTION_FPNFP_20200221.DAT &
gsutil cp gs://p-ascena-aadp-landing-01/pre/bi/arc/ANN_BI_TRANSACTION_FPNFP_20200222.DAT gs://p-ascena-aadp-landing-01/pre/bi/ANN_BI_TRANSACTION_FPNFP_20200222.DAT &
gsutil cp gs://p-ascena-aadp-landing-01/pre/bi/arc/ANN_BI_TRANSACTION_FPNFP_20200223.DAT gs://p-ascena-aadp-landing-01/pre/bi/ANN_BI_TRANSACTION_FPNFP_20200223.DAT &
gsutil cp gs://p-ascena-aadp-landing-01/pre/bi/arc/ANN_BI_TRANSACTION_FPNFP_20200224.DAT gs://p-ascena-aadp-landing-01/pre/bi/ANN_BI_TRANSACTION_FPNFP_20200224.DAT &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200111.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200111.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200112.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200112.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200129.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200129.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200130.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200130.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200131.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200131.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200201.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200201.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200202.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200202.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200203.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200203.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200204.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200204.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200205.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200205.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200206.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200206.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200207.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200207.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200208.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200208.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200209.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200209.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200210.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200210.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200211.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200211.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200212.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200212.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200213.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200213.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200214.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200214.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200215.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200215.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200216.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200216.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200217.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200217.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200218.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200218.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200219.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200219.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200220.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200220.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200221.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200221.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200222.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200222.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200223.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200223.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/dom/arc/ANN_DOM_BOPIS_TRANSACTIONS_20200224.dat gs://p-ascena-aadp-landing-01/pre/dom/ANN_DOM_BOPIS_TRANSACTIONS_20200224.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200130_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200130_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200131_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200131_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200203_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200203_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200204_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200204_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200205_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200205_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200206_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200206_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200207_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200207_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200210_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200210_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200211_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200211_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200212_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200212_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200213_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200213_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200214_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200214_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200217_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200217_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200218_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200218_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200219_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200219_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200220_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200220_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200221_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200221_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200222_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200222_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200223_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200223_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_EXCHRATE_20200224_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_EXCHRATE_20200224_001.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200120_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200120_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200128_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200128_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200130_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200130_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200131_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200131_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200201_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200201_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200202_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200202_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200203_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200203_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200204_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200204_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200205_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200205_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200206_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200206_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200207_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200207_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200208_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200208_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200209_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200209_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200210_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200210_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200211_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200211_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200212_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200212_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200213_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200213_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200214_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200214_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200215_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200215_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200216_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200216_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200217_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200217_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200218_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200218_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200219_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200219_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200220_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200220_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200221_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200221_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200222_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200222_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200223_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200223_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapd/arc/ANN_SAP_PROMO_20200224_001.dat gs://p-ascena-aadp-landing-01/pre/sapd/ANN_SAP_PROMO_20200224_001.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_PRODUCT_20200118_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_PRODUCT_20200118_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_PRODUCT_20200201_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_PRODUCT_20200201_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_PRODUCT_20200208_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_PRODUCT_20200208_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_PRODUCT_20200215_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_PRODUCT_20200215_001.dat &
#gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_PRODUCT_20200222_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_PRODUCT_20200222_001.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_PROMO_20200120_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_PROMO_20200120_001.dat &

gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STORE_20200118_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STORE_20200118_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STORE_20200201_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STORE_20200201_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STORE_20200208_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STORE_20200208_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STORE_20200215_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STORE_20200215_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STORE_20200222_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STORE_20200222_001.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STYLE_20200118_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STYLE_20200118_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STYLE_20200201_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STYLE_20200201_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STYLE_20200208_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STYLE_20200208_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STYLE_20200215_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STYLE_20200215_001.dat &
#gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_STYLE_20200222_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_STYLE_20200222_001.dat &
wait
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_VENDOR_20200216_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_VENDOR_20200216_001.dat &
gsutil cp gs://p-ascena-aadp-landing-01/pre/sapwm/arc/ANN_SAP_VENDOR_20200223_001.dat gs://p-ascena-aadp-landing-01/pre/sapwm/ANN_SAP_VENDOR_20200223_001.dat &
wait
