CREATE OR REPLACE VIEW ASCENA_STAGING_DEV.JUS_HST_PROMOTIONS_DRC
AS 
WITH MID AS
	(SELECT 
	TBL.PROMOTION_ID
	,MAX(TBL.BATCH_ID) OVER (PARTITION BY TBL.PROMOTION_ID) AS MAX_BATCH_ID
	FROM ASCENA_STAGING_DEV.JUS_HST_PROMOTIONS_20190105 TBL)
SELECT TBL1.* 
	FROM ASCENA_STAGING_DEV.JUS_HST_PROMOTIONS_20190105 TBL1
JOIN MID
	ON TBL1.BATCH_ID = MID.MAX_BATCH_ID
	AND TBL1.PROMOTION_ID = MID.PROMOTION_ID;