CREATE OR REPLACE VIEW ASCENA_STAGING_DEV.JUS_HST_PROMOTION_CELLS_DRC
AS 
WITH MID AS
(SELECT 
TBL.CELL_CODE
,TBL.PROMOTION_EXECUTION_ID
,MAX(TBL.BATCH_ID) OVER (PARTITION BY TBL.CELL_CODE,TBL.PROMOTION_EXECUTION_ID) AS MAX_BATCH_ID
FROM ASCENA_STAGING_DEV.JUS_HST_PROMOTION_CELLS_20190105 TBL)
SELECT TBL1.* 
FROM ASCENA_STAGING_DEV.JUS_HST_PROMOTION_CELLS_20190105 TBL1
JOIN MID
ON TBL1.BATCH_ID = MID.MAX_BATCH_ID	
AND TBL1.CELL_CODE = MID.CELL_CODE
AND TBL1.PROMOTION_EXECUTION_ID = MID.PROMOTION_EXECUTION_ID;