CREATE OR REPLACE VIEW ASCENA_STAGING_DEV.jus_hst_promotion_history_drc
AS
WITH MID AS
(SELECT 
MAX(TBL.BATCH_ID) as MAX_BATCH_ID
FROM ASCENA_STAGING_DEV.jus_hst_promotion_history_20190105 TBL)
SELECT * FROM ASCENA_STAGING_DEV.jus_hst_promotion_history_20190105 TBL1, MID
where TBL1.BATCH_ID = MID.MAX_BATCH_ID;
