CREATE OR REPLACE VIEW ASCENA_STAGING_DEV.jus_hst_transactions_drc
AS
WITH MID AS
(SELECT 
--MAX(TBL.BATCH_ID) OVER (PARTITION BY tbl.store_no,tbl.register_no,tbl.transaction_number,tbl.ship_date) AS MAX_BATCH_ID
MAX(TBL.BATCH_ID) as MAX_BATCH_ID
FROM ASCENA_STAGING_DEV.jus_hst_transactions_20190104 TBL)
SELECT * FROM ASCENA_STAGING_DEV.jus_hst_transactions_20190104 TBL1, MID
where TBL1.BATCH_ID = MID.MAX_BATCH_ID;
