echo "plus_tmci997_esp_outbound".bq >/${env_data_root}/ctl/plus_crm_esp_outbound_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci015_cust_ccard".bq >/${env_data_root}/ctl/plus_crm_cust_ccard_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci019_customer".bq >/${env_data_root}/ctl/plus_crm_customer_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci019_custonly".bq >/${env_data_root}/ctl/plus_crm_cust_only_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci021_cust_phone".bq >/${env_data_root}/ctl/plus_crm_cust_phone_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci079_club_memb".bq >/${env_data_root}/ctl/plus_crm_club_memb_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci105_chain_cust".bq >/${env_data_root}/ctl/plus_crm_chain_cust_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci172_chain_cust_email".bq >/${env_data_root}/ctl/plus_crm_chain_cust_email_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci173_full_email_addr_status".bq >/${env_data_root}/ctl/plus_crm_full_email_addr_status_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci173_full_email_address".bq >/${env_data_root}/ctl/plus_crm_full_email_address_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci180_cust_demog".bq >/${env_data_root}/ctl/plus_crm_cust_demog_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci396_curr_opt_in_out_full".bq >/${env_data_root}/ctl/plus_crm_curr_opt_in_out_full_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci972_chain_cust_fullemail".bq >/${env_data_root}/ctl/plus_crm_chain_cust_fullemail_${$}-`date +%m%d%H%M%S`.ctl
echo "plus_vmci995_esp_last_click_open".bq >/${env_data_root}/ctl/plus_crm_esp_last_click_open_${$}-`date +%m%d%H%M%S`.ctl
