diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_atg_returns.bq                        /home/svc_gcpintegnp/script_prodbackup_0519/ann_atg_returns.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_atg_transactions.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/ann_atg_transactions.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_aw_transactions_discountdtl.bq            /home/svc_gcpintegnp/script_prodbackup_0519/ann_aw_transactions_discountdtl.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_aw_transactions_header.bq                /home/svc_gcpintegnp/script_prodbackup_0519/ann_aw_transactions_header.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_aw_transactions_line.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/ann_aw_transactions_line.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_aw_transactions_linenotes.bq            /home/svc_gcpintegnp/script_prodbackup_0519/ann_aw_transactions_linenotes.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_aw_transactions_merchdtl.bq                /home/svc_gcpintegnp/script_prodbackup_0519/ann_aw_transactions_merchdtl.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_aw_transactions_returndtl.bq            /home/svc_gcpintegnp/script_prodbackup_0519/ann_aw_transactions_returndtl.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_aw_transactions_taxdetail.bq            /home/svc_gcpintegnp/script_prodbackup_0519/ann_aw_transactions_taxdetail.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_bi_transaction_fpnfp.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/ann_bi_transaction_fpnfp.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_dom_bopis_transactions.bq                /home/svc_gcpintegnp/script_prodbackup_0519/ann_dom_bopis_transactions.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_sap_exchrate.bq                            /home/svc_gcpintegnp/script_prodbackup_0519/ann_sap_exchrate.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_sap_product.bq                            /home/svc_gcpintegnp/script_prodbackup_0519/ann_sap_product.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_sap_store.bq                            /home/svc_gcpintegnp/script_prodbackup_0519/ann_sap_store.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_sap_style.bq                            /home/svc_gcpintegnp/script_prodbackup_0519/ann_sap_style.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/ann_sap_vendor.bq                            /home/svc_gcpintegnp/script_prodbackup_0519/ann_sap_vendor.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci067_cust_block.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci067_cust_block.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci079_club_memb.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci079_club_memb.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci105_chain_cust.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci105_chain_cust.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci172_chain_cust_email.bq            /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci172_chain_cust_email.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci173_full_email_address.bq            /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci173_full_email_address.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci173_full_email_addr_status.bq        /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci173_full_email_addr_status.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci180_cust_demog.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci180_cust_demog.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci396_curr_opt_in_out_full.bq        /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci396_curr_opt_in_out_full.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci972_chain_cust_fullemail.bq        /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci972_chain_cust_fullemail.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_vmci995_esp_last_click_open.bq            /home/svc_gcpintegnp/script_prodbackup_0519/plus_vmci995_esp_last_click_open.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/pre_acc_df_prod_hier.bq                        /home/svc_gcpintegnp/script_prodbackup_0519/pre_acc_df_prod_hier.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/pre_acc_df_prod_hier-csm.bq                    /home/svc_gcpintegnp/script_prodbackup_0519/pre_acc_df_prod_hier-csm.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_sales_customer.bq                        /home/svc_gcpintegnp/script_prodbackup_0519/plus_sales_customer.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_sales_transaction_detail.bq            /home/svc_gcpintegnp/script_prodbackup_0519/plus_sales_transaction_detail.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_sales_transaction_discount.bq            /home/svc_gcpintegnp/script_prodbackup_0519/plus_sales_transaction_discount.bq
diff /home/svc_gcpintegnp/script_prodbackup_dev/plus_sales_transaction_fee.bq                /home/svc_gcpintegnp/script_prodbackup_0519/plus_sales_transaction_fee.bq
